namespace: default
resources:
  - ../base
  - machine-deployment.yaml
  - gpu-operator-resources-set.yaml
patchesStrategicMerge:
  - patches/cluster.yaml
configMapGenerator:
  - name: nvidia-clusterpolicy-crd
    files:
      - clusterpolicy-crd.yaml
  - name: nvidia-gpu-operator-components
    files:
      - gpu-operator-components.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
