name: Lint Documentation
on:
  push:
    paths:
      - "**.md"
    branches:
      - main
  pull_request:
    paths: "**.md"
permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: tcort/github-action-markdown-link-check@a800ad5f1c35bf61987946fd31c15726a1c9f2ba # v1.1.0
      with:
        use-quiet-mode: 'yes'
        config-file: .markdownlinkcheck.json
